### ISSUE TITLE
Minor parsing and theming issues

### ISSUE THREAD

**Issue by h-2** [leafac/shiki-latex#4]
I have two problems, that the following snippet illustrates:

```tex
\documentclass{scrartcl}

\usepackage{realboxes}
\usepackage{fontspec}

\newfontfamily\UbuntuMono{Ubuntu Mono}
\setmonofont{Ubuntu Mono}

\usepackage[table,svgnames]{xcolor}
\definecolor{lightgrey}{rgb}{0.9,0.9,0.9}
\definecolor{dsolar_back}{HTML}{FDF6E3}
\definecolor{dsolar_text}{HTML}{657B83}
\definecolor{teal}{HTML}{94ccbe}

\usepackage[letterspace=60]{microtype}

\usepackage{minted}

\setminted[c++]{
    linenos=true,
    bgcolor=lightgrey,
    fontsize=\footnotesize,
%     style=solarizedlight,
%     style=solarized_light,
    frame=single,
    framesep=5pt,
    rulecolor=\color{lightgrey},
    stepnumber=2,
    numbersep=5pt,
    stripnl=false,
}

% Fix the frame overlapping the background
\makeatletter
\renewenvironment{minted@colorbg}[1]{
\setlength{\fboxsep}{\z@}
\def\minted@bgcol{#1}
\noindent
\begin{lrbox}{\minted@bgbox}
\begin{minipage}{\linewidth}}
{\end{minipage}
\end{lrbox}%
\colorbox{\minted@bgcol}{\usebox{\minted@bgbox}}}
\makeatother


\renewcommand\theFancyVerbLine{{\color{dsolar_text}\small\arabic{FancyVerbLine}}}

\renewcommand{\MintedPygmentize}{./node_modules/.bin/shiki-minted}

\usemintedstyle{Material-Theme-Ocean}

\begin{document}
\begin{minted}{c++}
auto visitor = [] (auto & val)
{
    if constexpr (std::integral<decltype(val)>)
        std::cout << val << " is a number\n";
    else if (std::same_as<decltype(val), std::string>)
        std::cout << val << " is a string\n";
};

std::variant<int, std::string> v = 3;              // declare variant and initialise to int-state
std::visit(visitor, v);                            // prints "3 is a number"

v = "foobar";                                      // destruct current value and store string
std::visit(visitor, v);                            // prints "foobar is a string"
\end{minted}
\end{document}
```
Output is:

![image](https://user-images.githubusercontent.com/2996863/77346042-76a98b00-6d2d-11ea-88dc-b9b857c2d028.png)

(ugly, just for demonstration purposes)

Problem 1) `\n` is incorrectly parsed in the string literals, it results in lot's of spaces being inserted (it should just be printed as-is).

Problem 2) Instructions for `fontStyle` are ignored. I have intentionally selected a default theme that has `italic` set for comments which is something my own theme does, as well. `bold` is also ignored for my own themes when I try to use it.

Thank you for providing this package, I am really happy with what I can currently produce with it :)

**Comment by leafac** [comment]
I fixed problem 1 in version `1.1.1` that I just released. Please `npm update shiki-latex`. And thanks for the bug report.

Problem 2 is [a current limitation of Shiki](https://github.com/octref/shiki/issues/15). Please go there and mention your interest. Once they have the feature there, I’ll add support for it here.

**Comment by h-2** [comment]
> I fixed problem 1 in version 1.1.1 that I just released. Please npm update shiki-latex. And thanks for the bug report.

Thank you!

> Problem 2 is a current limitation of Shiki. Please go there and mention your interest. Once they have the feature there, I’ll add support for it here.

I have posted over there! There is already experimental support in a PR. I have succeeded in patching my local install, but shiki-latex doesn't pick that up automatically... I guess that's expected? Would you add optional support for the experimental support or does that break shiki-latex with vanilla upstream?

**Comment by leafac** [comment]
> I have posted over there! There is already experimental support in a PR. I have succeeded in patching my local install, but shiki-latex doesn't pick that up automatically... I guess that's expected? Would you add optional support for the experimental support or does that break shiki-latex with vanilla upstream?

That’s expected. Shiki LaTeX will have to read the font style information produced by Shiki and generate the corresponding LaTeX. For example, it’ll have to read `font-weight: bold` and turn it into `\textbf{}`.

I’ll wait for the feature to be released in Shiki before I add support for it in Shiki LaTeX. If you want experimental support for the current [pull request](https://github.com/octref/shiki/pull/23), I encourage you to give it a try. And I’m looking forward for your pull request here 😃

**Comment by h-2** [comment]
> If you want experimental support for the current pull request, I encourage you to give it a try. And I’m looking forward for your pull request here

I have spent two hours on this now, but I can't get it to work. I think it would be enough to read `.fontStyle` in this line https://github.com/leafac/shiki-latex/blob/master/src/index.ts#L18 and add respective latex instructions, but I have never worked with Javascript or Typescript before and the whole process of creating a usable package from the PR branch seems to be quite complicated. I initially patched the source, but that doesn't seem to be enough as this has to be compiled to Javscript first? I found some tutorials that suggested `npx  tsc`, but that produces errors here :disappointed:

**Comment by leafac** [comment]
Here’s what I think you need to do.

### Build Shiki from the Pull Request

When you `npm install shiki` (or `npm install shiki-latex`, which will get `shiki` as well) you’re installing the version you find on the npm registry at https://www.npmjs.com/package/shiki. That’s usually what you want, but not this time, because you want the version in the Pull Request. So you have to build Shiki yourself using the code from the Pull Request.

To do this, first you have to install the tools Shiki’s using to manage the project: [Node.js](https://nodejs.org) (but you already have that) and [Yarn](https://yarnpkg.com) (which I figure they’re using because of the `yarn.lock` file in the codebase).

Next, clone Shiki from the branch with the Pull Request: https://github.com/mrinalini-m/shiki/tree/feat/font-style

```console
$ git clone git@github.com:mrinalini-m/shiki.git
$ cd shiki
$ git checkout feat/font-style
```

Now you should be able to build Shiki. I’ve never used the build tools that Shiki’s using (instead of Yarn I use npm, and I’ve never needed [Lerna](https://lerna.js.org) (which I figure they’re using because of the `lerna.json` file in the codebase), because all my projects are single packages), but judging by a 5-minute scan of their documentation I guess it’d go like this:

```console
$ yarn install
$ yarn run lerna bootstrap
```

### Use the Local Version of Shiki in Shiki LaTeX

Clone Shiki LaTeX, and tell npm to use the local version of Shiki:

```console
$ npm install
$ npm link <path-to-the-shiki-repository>/packages/shiki/
```

### Modify Code

I think you’re on the right track with what you proposed. You may change [this line](https://github.com/leafac/shiki-latex/blob/master/src/index.ts#L18) to include the `fontStyle`: `{ content, color, fontStyle }`. Then use the `fontStyle` to generate LaTeX: `\textbf{}`, `\textit{}`, and `\underline{}`.

Build Shiki LaTeX with:

```console
$ npx tsc
```

I recommend you also write some tests, which you may run with:

```console
$ npm test
```

### Use the Patched Version of Shiki LaTeX in Your Document

In your LaTeX project, run something similar to what you used to link between Shiki LaTeX and Shiki itself:

```console
$ npm link <path-to-the-shiki-latex>
```

---

Then you’re ready to send the Pull Request. 😃

**Comment by h-2** [comment]
Thanks for the HowTo, I will give it a try in the next days!

**Comment by leafac** [comment]
I opened #7 where we can continue this conversation.
